services:
  web:
    build:
      context: ./djangoAirbnb_backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./djangoAirbnb_backend:/usr/src/djangobnb_backend
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: djangobnb        # must match SQL_DATABASE
      POSTGRES_USER: bnbuser        # must match SQL_USER
      POSTGRES_PASSWORD: password  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: